### ISSUE TITLE
Initializing part GitFlowActionSection error

### ISSUE THREAD

**Issue by veccie** [jakobehn/GitFlow.VS#22]
When going to the GitFlow section for the first time I get an error(see stacktrace below):

Another thing, I have a project where I installed GitFlow(using v0.9.23), but when opening this project on another PC(newest version) I get the install button, even though I can see the gitflow entries under repository settings(other). I don't get any errors though.
```
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitFlowVS.Extension.GitFlowActionSection". ---> System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.
   at LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj) in :line 0
   at System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
   at LibGit2Sharp.Core.NativeMethods.git_repository_open(RepositorySafeHandle& repository, FilePath path)
   at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options)
   at GitFlow.VS.GitFlowWrapper.get_IsInitialized()
   at GitFlow.VS.GitFlowWrapper.get_IsOnFeatureBranch()
   at GitFlowVS.Extension.ViewModels.ActionViewModel.set_ShowFinishFeature(Visibility value)
   at GitFlowVS.Extension.ViewModels.ActionViewModel..ctor(GitFlowActionSection te)
   at GitFlowVS.Extension.GitFlowActionSection..ctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass4`2.<CreateStronglyTypedExportFactoryOfTM>b__5()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()
```

**Comment by jakobehn** [comment]
Thanks for the report. Is this VS2013 or VS2015?

Regarding the other question, you must run the install on every machine, since it installs the GitFlow scripts and dependent tools that are used by the extension

**Comment by veccie** [comment]
VS2015

Ok, thanks

**Comment by jakobehn** [comment]
I just uploaded a new version that should solve the problem. Sorry for the inconvenience
