### ISSUE TITLE
Can't install on VS 2017 Enterprise 15.2 (26430.6)

### ISSUE THREAD

**Issue by omaximenco** [jakobehn/GitFlow.VS#62]
5/18/2017 8:14:37 AM - Microsoft VSIX Installer
5/18/2017 8:14:37 AM - -------------------------------------------
5/18/2017 8:14:37 AM - Initializing Install...
5/18/2017 8:14:37 AM - Extension Details...
5/18/2017 8:14:37 AM - 	Identifier         : cf9a97a9-f7c4-4ca0-bf48-f56b0d816451
5/18/2017 8:14:37 AM - 	Name               : GitFlow for Visual Studio 2017
5/18/2017 8:14:37 AM - 	Author             : Jakob Ehn
5/18/2017 8:14:37 AM - 	Version            : 1.2.2.0
5/18/2017 8:14:37 AM - 	Description        : Integrates GitFlow in Visual Studio 2017
5/18/2017 8:14:37 AM - 	Locale             : en-US
5/18/2017 8:14:37 AM - 	MoreInfoURL        : https://github.com/jakobehn/GitFlow.VS
5/18/2017 8:14:37 AM - 	InstalledByMSI     : False
5/18/2017 8:14:37 AM - 	SupportedFrameworkVersionRange : [4.5,)
5/18/2017 8:14:37 AM - 
5/18/2017 8:14:37 AM - 	SignatureState     : Unsigned
5/18/2017 8:14:37 AM - 	Supported Products : 
5/18/2017 8:14:37 AM - 		Microsoft.VisualStudio.Community
5/18/2017 8:14:37 AM - 			Version : [15.0]
5/18/2017 8:14:37 AM - 
5/18/2017 8:14:37 AM - 	References         : 
5/18/2017 8:14:37 AM - 		-------------------------------------------------------
5/18/2017 8:14:37 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
5/18/2017 8:14:37 AM - 		Name         : Visual Studio MPF 15.0
5/18/2017 8:14:37 AM - 		Version      : [15.0]
5/18/2017 8:14:37 AM - 		MoreInfoURL  : 
5/18/2017 8:14:37 AM - 		Nested       : No
5/18/2017 8:14:37 AM - 
5/18/2017 8:14:37 AM - Signature Details...
5/18/2017 8:14:37 AM - 	Extension is not signed.
5/18/2017 8:14:37 AM - 
5/18/2017 8:14:37 AM - Searching for applicable products...
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Ultimate 2012
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Premium 2012 
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Professional 2012
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Ultimate 2013
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Premium 2013 
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Professional 2013
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Professional 2015
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio Community 2015
5/18/2017 8:14:39 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/18/2017 8:14:39 AM - Found installed product - Global Location
5/18/2017 8:14:39 AM - Found installed product - ssms
5/18/2017 8:14:39 AM - Found installed product - ssms
5/18/2017 8:14:39 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by omaximenco** [comment]
Not sure what happened but this time it worked. Closing...
