### ISSUE TITLE
GetAllBranchesThatStartsWithConfigPrefix throws exception

### ISSUE THREAD

**Issue by demoncodemonkey** [jakobehn/GitFlow.VS#63]
I can't get the extension to work. Every time I open the Gitflow window from Team Explorer, this exception is shown:

`Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "GitFlowVS.Extension.GitFlowActionSection". ---> System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at GitFlow.VS.GitFlowWrapper.<>c__DisplayClass37_0.<GetAllBranchesThatStartsWithConfigPrefix>b__1(Branch b)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitFlow.VS.GitFlowWrapper.GetAllBranchesThatStartsWithConfigPrefix(String config)
   at GitFlow.VS.GitFlowWrapper.get_AllReleases()
   at GitFlowVS.Extension.ViewModels.ActionViewModel.get_AllReleases()
   at GitFlowVS.Extension.ViewModels.ActionViewModel.set_ShowFinishRelease(Visibility value)
   at GitFlowVS.Extension.ViewModels.ActionViewModel..ctor(GitFlowActionSection te)
   at GitFlowVS.Extension.GitFlowActionSection..ctor()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExportFactoryExport>b__1()
   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass54_0.<CreateExportFactory>b__0()
   at Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.ComposablePartDefinitionForExportFactory.CreatePart()
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.LifetimeContext.GetExportLifetimeContextFromExport[T](Export export)
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass6_0`2.<CreateStronglyTypedExportFactoryOfTM>b__0()
   at System.ComponentModel.Composition.ExportFactory`1.CreateExport()
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Create()`

I've tried installing Git For Windows and then reinstalling the extension, I've also tried running "gitflow-installer.sh install stable" as suggested from another thread, but it made no difference.
I'm using VS2017 Pro, using Git in VSTS.
Any ideas?

**Comment by demoncodemonkey** [comment]
I fixed it by opening git bash, running `git flow init -f` and filling in the details with some value. I guess I did this wrong the first time...
